### ISSUE TITLE
Error at Denoising Stage

### ISSUE THREAD

**Issue by faizansaleem-1992** [DominikBuchner/apscale#10]
Hi Dominik,

APSCALE works well. However, for some reason, it gives an error after OTU clustering (at the denoising stage, I think). I put both sequencing files (separate) in the demultiplexing folder for processing. I have attached all the files I used as a test run and the error screenshot. I got the OTU table, but the pipeline did not provide the ESV table. I have provided the files, but GitHub is not allowing me to upload sequencing files (upload limit of 25 MB). If you could look at it, I would appreciate it. Thank you very much for all your help!

Best regards,

Faizan Saleem
![APSCALE-Error](https://github.com/DominikBuchner/apscale/assets/144712628/9de014d0-e6bb-4e94-973d-e24cad4ac439)
[Project_report.xlsx](https://github.com/DominikBuchner/apscale/files/12578193/Project_report.xlsx)
[Settings.xlsx](https://github.com/DominikBuchner/apscale/files/12578194/Settings.xlsx)

**Comment by MerjanK** [comment]
Hi, I'm also having a similar issue. I've tried running apscale and apscale_gui in both MacOS and Windows and in all of them I got an error at the denoising stage, similar to Faizan I got the OTU table but couldn't get the ESV table. I'd appreaciate any insight on how to solve this problem. 

Thanks in advance and thanks for developing apscale :)

Merjan.

This is the error I got :

Generating OTU table: 100%|███████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 405.80it/s]
20:11:08: Lines written to OTU table: 80 lines [00:00, 3469.66 lines/s]
20:11:08: Saving the OTU table to excel. This may take a while.
20:11:08: OTU table saved to D:\Apscale\Arda-COI_apscale\7_otu_clustering\Arda-COI_apscale_OTU_table.xlsx.
20:11:08: Saving the OTU table to parquet. This may take a while.
20:11:08: OTU table saved to D:\Apscale\Arda-COI_apscale\7_otu_clustering\Arda-COI_apscale_OTU_table.parquet.snappy.
20:11:08: Starting denoising. This may take a while.
20:11:08: Denoised unique 57 sequences into 29 ESVs.
20:11:08: Starting chimera removal from the OTUs. This may take a while.
20:11:08: 0 chimeras removed from 29 ESV sequences.
20:11:08: ESVs saved to D:\Apscale\Arda-COI_apscale\7_otu_clustering\Arda-COI_apscale_OTUs.fasta.
20:11:08: Starting to remap 15 input files.
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "c:\users\marja\appdata\local\programs\python\python39\lib\site-packages\joblib\externals\loky\process_executor.py", line 463, in _process_worker
    r = call_item()
  File "c:\users\marja\appdata\local\programs\python\python39\lib\site-packages\joblib\externals\loky\process_executor.py", line 291, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "c:\users\marja\appdata\local\programs\python\python39\lib\site-packages\joblib\parallel.py", line 589, in __call__
    return [func(*args, **kwargs)
  File "c:\users\marja\appdata\local\programs\python\python39\lib\site-packages\joblib\parallel.py", line 589, in <listcomp>
    return [func(*args, **kwargs)
  File "c:\users\marja\appdata\local\programs\python\python39\lib\site-packages\apscale\g_denoising.py", line 186, in remapping_esv
    exact_matches = re.findall("Matching query sequences: (\d+)", content)[0]
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\marja\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\marja\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\marja\AppData\Local\Programs\Python\Python39\Scripts\apscale.exe\__main__.py", line 7, in <module>
  File "c:\users\marja\appdata\local\programs\python\python39\lib\site-packages\apscale\__main__.py", line 134, in main
    g_denoising.main(args.run_apscale)
  File "c:\users\marja\appdata\local\programs\python\python39\lib\site-packages\apscale\g_denoising.py", line 279, in main
    Parallel(n_jobs=cores)(
  File "c:\users\marja\appdata\local\programs\python\python39\lib\site-packages\joblib\parallel.py", line 1952, in __call__
    return output if self.return_generator else list(output)
  File "c:\users\marja\appdata\local\programs\python\python39\lib\site-packages\joblib\parallel.py", line 1595, in _get_outputs
    yield from self._retrieve()
  File "c:\users\marja\appdata\local\programs\python\python39\lib\site-packages\joblib\parallel.py", line 1699, in _retrieve
    self._raise_error_fast()
  File "c:\users\marja\appdata\local\programs\python\python39\lib\site-packages\joblib\parallel.py", line 1734, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "c:\users\marja\appdata\local\programs\python\python39\lib\site-packages\joblib\parallel.py", line 736, in get_result
    return self._return_or_raise()
  File "c:\users\marja\appdata\local\programs\python\python39\lib\site-packages\joblib\parallel.py", line 754, in _return_or_raise
    raise self._result
IndexError: list index out of range

**Comment by DominikBuchner** [comment]
I'm investigating this at the moment and try to fix it. However, I'm not sure why this pops up at the moment, since I did not change the denoising code. Maybe vsearch was updated.. I'll dig for a solution.

**Comment by MerjanK** [comment]
Here is the vsearch version vsearch v2.23.0_macos_x86_64. I have the same version for Windows as well.

**Comment by DominikBuchner** [comment]
Would you mind testing if downgrading to 2.22 fixes the issue? If so, I'll push an update for 2.23 soon however this might brake backwards compatibility, so I'll have to think of a good solution.

**Comment by MerjanK** [comment]
Yeah I just tested it at first with version 2.19 but got another similar error then tried 2.22 and it worked. Thanks!

**Comment by faizansaleem-1992** [comment]
Hi Dominik,

Yeah, it worked with vsearch version 2.22.1. I don’t know what was the issue. Thanks a lot for your time.

**Comment by DominikBuchner** [comment]
I'll take care of fixing the code so that it works with up to date vsearch!

**Comment by DominikBuchner** [comment]
Hi Faizan,
yes the adaptor sequences should be removed before. However this is usually done by the company that does the sequencing for us. If you have your own sequencer you'd have to remove them before analysis. However, it MIGHT be possible, that cutadapt removes them with the primers, but I'm not 100% sure about that.

**Comment by faizansaleem-1992** [comment]
Thanks for the guidance. I just checked, and Cutadapt does remove the adapters automatically.

**Comment by DominikBuchner** [comment]
Fixed with version 1.7.1
