### ISSUE TITLE
OTU clustering Error

### ISSUE THREAD

**Issue by AlvaroFueyo** [DominikBuchner/apscale#13]
class 'ValueError" in OTU clustering When a library has 0 reads.

Vsearch 2.27.

When I downgrade to vsearch 2.20.1, there is no such problem.

**Error:**

joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\afuey\AppData\Local\Programs\Python\Python39\lib\site-packages\joblib\externals\loky\process_executor.py", line 463, in _process_worker
    r = call_item()
  File "C:\Users\afuey\AppData\Local\Programs\Python\Python39\lib\site-packages\joblib\externals\loky\process_executor.py", line 291, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "C:\Users\afuey\AppData\Local\Programs\Python\Python39\lib\site-packages\joblib\parallel.py", line 589, in __call__
    return [func(*args, **kwargs)
  File "C:\Users\afuey\AppData\Local\Programs\Python\Python39\lib\site-packages\joblib\parallel.py", line 589, in <listcomp>
    return [func(*args, **kwargs)
  File "C:\Users\afuey\AppData\Local\Programs\Python\Python39\lib\site-packages\apscale\f_otu_clustering.py", line 182, in remapping
    otu_tab = otu_tab.set_axis(["ID", sample_name_out], axis=1, copy=False)
  File "C:\Users\afuey\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\frame.py", line 5344, in set_axis
    return super().set_axis(labels, axis=axis, copy=copy)
  File "C:\Users\afuey\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\generic.py", line 791, in set_axis
    return self._set_axis_nocheck(labels, axis, inplace=False, copy=copy)
  File "C:\Users\afuey\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\generic.py", line 803, in _set_axis_nocheck
    setattr(obj, obj._get_axis_name(axis), labels)
  File "C:\Users\afuey\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\generic.py", line 6310, in __setattr__
    return object.__setattr__(self, name, value)
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "C:\Users\afuey\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\generic.py", line 813, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "C:\Users\afuey\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\internals\managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "C:\Users\afuey\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\internals\base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 1 elements, new values have 2 elements
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\afuey\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\afuey\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\afuey\AppData\Local\Programs\Python\Python39\Scripts\apscale_gui.exe\__main__.py", line 7, in <module>
  File "C:\Users\afuey\AppData\Local\Programs\Python\Python39\lib\site-packages\apscale_gui\__main__.py", line 496, in main
    otu_clustering(str(path_to_outdirs))
  File "C:\Users\afuey\AppData\Local\Programs\Python\Python39\lib\site-packages\apscale\f_otu_clustering.py", line 271, in main
    Parallel(n_jobs=cores)(
  File "C:\Users\afuey\AppData\Local\Programs\Python\Python39\lib\site-packages\joblib\parallel.py", line 1952, in __call__
    return output if self.return_generator else list(output)
  File "C:\Users\afuey\AppData\Local\Programs\Python\Python39\lib\site-packages\joblib\parallel.py", line 1595, in _get_outputs
    yield from self._retrieve()
  File "C:\Users\afuey\AppData\Local\Programs\Python\Python39\lib\site-packages\joblib\parallel.py", line 1699, in _retrieve
    self._raise_error_fast()
  File "C:\Users\afuey\AppData\Local\Programs\Python\Python39\lib\site-packages\joblib\parallel.py", line 1734, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "C:\Users\afuey\AppData\Local\Programs\Python\Python39\lib\site-packages\joblib\parallel.py", line 736, in get_result
    return self._return_or_raise()
  File "C:\Users\afuey\AppData\Local\Programs\Python\Python39\lib\site-packages\joblib\parallel.py", line 754, in _return_or_raise
    raise self._result
ValueError: Length mismatch: Expected axis has 1 elements, new values have 2 elements

**Comment by DominikBuchner** [comment]
Please move this issue to apscale_gui, this is not the originated in the core code of apscale itself.
