### ISSUE TITLE
Issue with --denoising in Apscale/2.0.3

### ISSUE THREAD

**Issue by KarolineBruunDegn** [DominikBuchner/apscale#18]
Dear Dominik. 

When running the --denoising step in Apscale/2.0.3, the pipeline fails with the following error trace (pasted below).
Specifically, the pipeline cannot parse certain expected outputs, possibly from the vsearch log file.
Additionally, warnings about invalid escape sequences (\d and \w) are observed, 

The previous module of the Apscale pipeline "6_dereplication" worked fine.

Hope you can help me :)

Best,
Karoline

------
[kardeg@g-12-l0002 Anholt_Apscale_Analysis_apscale]$ apscale --denoising
10:22:07: Starting individual denoising and chimera removal.
<unknown>:1: SyntaxWarning: invalid escape sequence '\d'
<unknown>:1: SyntaxWarning: invalid escape sequence '\w'
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/services/tools/apscale/2.0.3/lib/python3.12/site-packages/apscale/f_denoising.py", line 66, in denoise
    re.findall("(\d+) seqs, min ", content)[0],
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/services/tools/apscale/2.0.3/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py", line 463, in _process_worker
    r = call_item()
        ^^^^^^^^^^^
  File "/services/tools/apscale/2.0.3/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py", line 291, in __call__
    return self.fn(*self.args, **self.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/services/tools/apscale/2.0.3/lib/python3.12/site-packages/joblib/parallel.py", line 598, in __call__
    return [func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/services/tools/apscale/2.0.3/lib/python3.12/site-packages/apscale/f_denoising.py", line 73, in denoise
    version = re.findall("vsearch ([\w\.]*)", content)[0]
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/services/tools/apscale/2.0.3/bin/apscale", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/services/tools/apscale/2.0.3/lib/python3.12/site-packages/apscale/__main__.py", line 158, in main
    f_denoising.main()
  File "/services/tools/apscale/2.0.3/lib/python3.12/site-packages/apscale/f_denoising.py", line 259, in main
    Parallel(n_jobs=cores)(
  File "/services/tools/apscale/2.0.3/lib/python3.12/site-packages/joblib/parallel.py", line 2007, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "/services/tools/apscale/2.0.3/lib/python3.12/site-packages/joblib/parallel.py", line 1650, in _get_outputs
    yield from self._retrieve()
  File "/services/tools/apscale/2.0.3/lib/python3.12/site-packages/joblib/parallel.py", line 1754, in _retrieve
    self._raise_error_fast()
  File "/services/tools/apscale/2.0.3/lib/python3.12/site-packages/joblib/parallel.py", line 1789, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "/services/tools/apscale/2.0.3/lib/python3.12/site-packages/joblib/parallel.py", line 745, in get_result
    return self._return_or_raise()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/services/tools/apscale/2.0.3/lib/python3.12/site-packages/joblib/parallel.py", line 763, in _return_or_raise
    raise self._result
IndexError: list index out of range

**Comment by DominikBuchner** [comment]
This was an error related to the latest vsearch update and has been fixed with Apscale v 2.0.4
