### ISSUE TITLE
Pandas.Error during primer trimming

### ISSUE THREAD

**Issue by SaschaKrenek** [DominikBuchner/apscale#5]
Hi;
I'm experiencing an issue during the primer trimming step:

Starting primer trimming
12:44:10: Starting to trim primers of 2 input files.
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py", line 436, in _process_worker
    r = call_item()
  File "/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py", line 288, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/dist-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/apscale/c_primer_trimming.py", line 31, in primer_trimming
    log_df = pd.read_csv(StringIO(f.stdout.decode('ascii', errors = 'ignore')), sep = '\t')
  File "/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 934, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 1236, in _make_engine
    return mapping[engine](f, **self.options)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/c_parser_wrapper.py", line 75, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 551, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/apscale_gui/__main__.py", line 874, in <module>
    main()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/apscale_gui/__main__.py", line 479, in main
    primer_trimming(str(path_to_outdirs))
  File "/usr/local/lib/python3.10/dist-packages/apscale/c_primer_trimming.py", line 74, in main
    Parallel(n_jobs = cores)(delayed(primer_trimming)(file, project = project, p5_primer = p5_primer, p7_primer = p7_primer, anchoring = anchoring) for file in input)
  File "/usr/local/lib/python3.10/dist-packages/joblib/parallel.py", line 1056, in __call__
    self.retrieve()
  File "/usr/local/lib/python3.10/dist-packages/joblib/parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/local/lib/python3.10/dist-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
pandas.errors.EmptyDataError: No columns to parse from file

I've tested it on VMs with Ubuntu 20.04 and 22.04 with Python 3.8 and 3.10, and always get the same error.

Thanks,
Sascha

**Comment by DominikBuchner** [comment]
Can you downgrade to cutadapt 3.5 and check if the error still persists?

**Comment by SaschaKrenek** [comment]
It still gives me the same error with cutadapt 3.5 and the log file is not written. Both apscale and cutadapt have been installed as root, could this cause a permission issue?

I've attached the PE-merge files:
[Z1-2-P1_PE.fastq.gz](https://github.com/DominikBuchner/apscale/files/9221077/Z1-2-P1_PE.fastq.gz)
[Z1-2-P2_PE.fastq.gz](https://github.com/DominikBuchner/apscale/files/9221078/Z1-2-P2_PE.fastq.gz)

Forward Primer is: GGWACWGGWTGAACWGTWTAYCCYCC
Reverse Primer is: TAIACYTCIGGRTGICCRAARAAYCA

**Comment by DominikBuchner** [comment]
Check your primers. The letter "I" is not part of the IUPAC ambiguity code and probably has to be replaced with N :) Will add a failsafe to prevent this from happening.

**Comment by SaschaKrenek** [comment]
That's the trick ヽ(´▽`)/

Thanks!!!
